spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///product?useSSL=false
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.kaishengit.entity
  mapper-locations: classpath:mapper/*.xml
redis:
  host: 192.168.142.13
  port: 6379
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql